name: initial-deployment

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and Deploy to Azure
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      # Azure Login using Service Principal
      - name: Sign in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login to Azure Container Registry
      - name: Azure Container Registry Login
        run: |
          az acr login --name yassindevacr

      # Build and push Docker image to ACR
      - name: Build and Push Docker image
        run: |
          IMAGE_NAME="yassindevacr.azurecr.io/clickcounter:${GITHUB_SHA}"
          docker build -f src/v1/Dockerfile -t $IMAGE_NAME src/v1
          docker push $IMAGE_NAME

      # Deploy to Azure Web App (Production)
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "yassindev-app"
          images: "yassindevacr.azurecr.io/clickcounter:${{ github.sha }}"

      # Optional: Tail logs (for verification only)
      - name: Check Azure App Logs
        run: az webapp log tail --name yassindev-app --resource-group yassindev-rg
